---
apiVersion: autoscaling.tsm.tanzu.vmware.com/v1alpha1
kind: Definition
metadata:
  name: asd-shopping
  namespace: acme
  labels:
    app: shopping
    version: v1
    release: demo
spec:
  scaleTargetRef:
    kubernetes:
      kind: Deployment
      name: shopping
  scaleRule:
    mode: EFFICIENCY
    enabled: true
    instances:
      min: 1
      max: 10
    trigger:
      gracePeriodSeconds: 90
      metric:
        name: p99Latency
        scaleUp: 750
        scaleDown: 400
        windowSeconds: 60

