---
apiVersion: autoscaling.tsm.tanzu.vmware.com/v1alpha1
kind: Definition
metadata:
  name: asd-productpage
  namespace: bookinfo
  labels:
    app: productpage
    version: v1
    release: demo
spec:
  scaleTargetRef:
    kubernetes:
      kind: Deployment
      name: productpage-v1
  scaleRule:
    mode: EFFICIENCY
    enabled: true
    instances:
      min: 1
      max: 16
    trigger:
      gracePeriodSeconds: 90
      metric:
        name: CPUUsagePercent
        scaleUp: 90
        scaleDown: 50
---
apiVersion: autoscaling.tsm.tanzu.vmware.com/v1alpha1
kind: Definition
metadata:
  name: asd-details
  namespace: bookinfo
  labels:
    app: details
    version: v1
    release: demo
spec:
  scaleTargetRef:
    kubernetes:
      kind: Deployment
      name: details-v1
  scaleRule:
    mode: EFFICIENCY
    enabled: true
    instances:
      min: 1
      max: 10
    trigger:
      gracePeriodSeconds: 90
      metric:
        name: CPUUsagePercent
        scaleUp: 80
        scaleDown: 50
---
apiVersion: autoscaling.tsm.tanzu.vmware.com/v1alpha1
kind: Definition
metadata:
  name: asd-reviews-v2
  namespace: bookinfo
  labels:
    app: reviews
    version: v2
    release: demo
spec:
  scaleTargetRef:
    kubernetes:
      kind: Deployment
      name: reviews-v2
  scaleRule:
    mode: EFFICIENCY
    enabled: true
    instances:
      min: 1
      max: 10
    trigger:
      gracePeriodSeconds: 90
      metric:
        name: CPUUsagePercent
        scaleUp: 80
        scaleDown: 50
---
apiVersion: autoscaling.tsm.tanzu.vmware.com/v1alpha1
kind: Definition
metadata:
  name: asd-ratings-v1
  namespace: bookinfo
  labels:
    app: ratings
    version: v1
    release: demo
spec:
  scaleTargetRef:
    kubernetes:
      kind: Deployment
      name: ratings-v1
  scaleRule:
    mode: EFFICIENCY
    enabled: true
    instances:
      min: 1
      max: 10
    trigger:
      gracePeriodSeconds: 90
      metric:
        name: CPUUsagePercent
        scaleUp: 80
        scaleDown: 50
