version: '3'

services:
  catalog-db:
       image: gcr.io/vmwarecloudadvocacy/acmeshop-catalog-db:latest
       hostname: catalog-db
       environment:
        - MONGO_INITDB_ROOT_USERNAME=mongoadmin
        - MONGO_INITDB_ROOT_PASSWORD=secret
        - MONGO_INITDB_DATABASE=acmefit
       cap_add:
        - CHOWN
        - SETGID
        - SETUID
  catalog:
        image: gcr.io/vmwarecloudadvocacy/acmeshop-catalog:stable
        hostname: catalog
        restart: always
        ports:
          - '8082:8082'
        cap_add:
          - NET_BIND_SERVICE
        environment:
             - CATALOG_DB_USERNAME=mongoadmin
             - CATALOG_DB_PASSWORD=secret
             - CATALOG_DB_HOST=catalog-db
             - CATALOG_PORT=8082
             - CATALOG_DB_PORT=27017
             - CATALOG_VERSION=v1
             - USERS_HOST=0.0.0.0
             - USERS_PORT=8083
             - JAEGER_AGENT_HOST='localhost'
             - JAEGER_AGENT_PORT=6831
        depends_on:
             - catalog-db
