---
apiVersion: v1
kind: Secret
metadata:
  name: redis-pass
type: Opaque
data:
  password: cGFzc3dvcmQ=
---
apiVersion: v1
kind: Secret
metadata:
  name: catalog-mongo-pass
type: Opaque
data:
  password: cGFzc3dvcmQ=
---
apiVersion: v1
kind: Secret
metadata:
  name: order-mongo-pass
type: Opaque
data:
  password: cGFzc3dvcmQ=
---
apiVersion: v1
kind: Secret
metadata:
  name: users-mongo-pass
type: Opaque
data:
  password: cGFzc3dvcmQ=
---
