apiVersion: v1
kind: Service
metadata:
  name: users-mongo
  labels:
    app: acmefit-users-db-total
    service: users-db
spec:
  ports:
    - port: 27017
      name: mongo-users
      protocol: TCP
  selector:
    app: acmefit-users-db-total
    service: users-db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-mongo
  labels:
    app: acmefit-users-db-total
    service: users-db
spec:
  selector:
    matchLabels:
      app: acmefit-users-db-total  # has to match .spec.template.metadata.labels
      service: users-db
  replicas: 1
  template:
    metadata:
      labels:
        app: acmefit-users-db-total  # has to match .spec.selector.matchLabels
        service: users-db
    spec:
      containers:
        - name: users-mongo
          image: mongo:4
          resources:
            {}
          ports:
            - name: mongo-users
              containerPort: 27017
              protocol: "TCP"
          env:
          - name: MONGO_INITDB_ROOT_USERNAME
            value: 'mongoadmin'
          - name: MONGO_INITDB_DATABASE
            value: 'acmefit'
          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: users-mongo-pass
                key: password
          volumeMounts:
            - mountPath: /data/db
              name: mongodata
            - mountPath: /docker-entrypoint-initdb.d
              name: mongo-initdb
      volumes:
        - name: mongodata
          emptyDir: {}
        - name: mongo-initdb
          configMap:
            name: users-initdb-config
#        - name: mongodata
#          persistentVolumeClaim:
#            claimName: mongodata
